name: Ultimate Final Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip build-essential libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libffi-dev libssl-dev

    - name: Install Python packages
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" kivy kivymd plyer firebase-admin bcrypt cryptography buildozer

    - name: Run Buildozer (and pre-accept licenses)
      run: |
        source venv/bin/activate
        # This will trigger the initial SDK download inside ./.buildozer
        # and then immediately accept the licenses before the main build.
        # The '|| true' ensures the command doesn't fail if there's nothing to accept yet.
        yes | buildozer android p4a -- sdkmanager --licenses || true
        # Now run the actual build command
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: eldercare-apk
        path: bin/*.apk
        if-no-files-found: error