name: Final Corrected Manual Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip build-essential libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libffi-dev libssl-dev

    - name: Manually download and set up Android SDK
      run: |
        SDK_ROOT=$GITHUB_WORKSPACE/android-sdk
        echo "SDK_ROOT=$SDK_ROOT" >> $GITHUB_ENV
        
        # Download and extract cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $SDK_ROOT
        
        # CORRECT WAY: Rename the extracted folder to 'latest'
        mv $SDK_ROOT/cmdline-tools $SDK_ROOT/latest
        
        # Now the path is correct: $SDK_ROOT/latest/bin/sdkmanager
        echo "ANDROID_HOME=$SDK_ROOT" >> $GITHUB_ENV
        
        # Accept all licenses
        yes | $SDK_ROOT/latest/bin/sdkmanager --licenses
        
        # Install necessary platform and build tools
        $SDK_ROOT/latest/bin/sdkmanager "platforms;android-31" "build-tools;30.0.3" "platform-tools"

    - name: Install Python packages
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" kivy kivymd plyer firebase-admin bcrypt cryptography buildozer

    - name: Run Buildozer
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: eldercare-apk
        path: bin/*.apk
        if-no-files-found: error