name: Manual Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Using a stable LTS version

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          build-essential \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libffi-dev \
          libssl-dev

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0"
        pip install kivy
        pip install kivymd plyer firebase-admin bcrypt cryptography buildozer

    - name: Run Buildozer
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: eldercare-apk
        path: bin/*.apk