name: Final Manual Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Using a stable LTS version

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip build-essential libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libffi-dev libssl-dev

    - name: Manually download and set up Android SDK
      run: |
        # Create SDK directory and navigate into it
        mkdir -p android-sdk
        cd android-sdk
        # Download and extract cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip
        # Fix directory structure
        mv cmdline-tools latest
        # Set environment variable for the SDK root
        echo "ANDROID_HOME=$PWD" >> $GITHUB_ENV
        # Accept all licenses
        yes | latest/bin/sdkmanager --licenses
        # Install necessary platform and build tools
        latest/bin/sdkmanager "platforms;android-31" "build-tools;30.0.3" "platform-tools"

    - name: Install Python packages
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" kivy kivymd plyer firebase-admin bcrypt cryptography buildozer

    - name: Run Buildozer
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: eldercare-apk
        path: bin/*.apk
        if-no-files-found: error # This will make the job fail if no APK is found