name: Final Android APK Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip build-essential libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libffi-dev libssl-dev

    - name: Manually download and set up Android SDK
      run: |
        # Create SDK directory
        mkdir -p $HOME/android_sdk/cmdline-tools
        # Download and extract cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip -d $HOME/android_sdk/cmdline-tools
        # Fix directory structure
        mv $HOME/android_sdk/cmdline-tools/cmdline-tools $HOME/android_sdk/cmdline-tools/latest
        # Accept all licenses
        yes | $HOME/android_sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/android_sdk
        # Install necessary packages
        $HOME/android_sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-31" "build-tools;30.0.3" --sdk_root=$HOME/android_sdk

    - name: Install Python packages
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" kivy kivymd plyer firebase-admin bcrypt cryptography buildozer

    - name: Run Buildozer
      env:
        ANDROID_HOME: ${{ env.HOME }}/android_sdk
        ANDROID_SDK_ROOT: ${{ env.HOME }}/android_sdk
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: eldercare-apk
        path: bin/*.apk